# Generated by Django 3.1.7 on 2021-03-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('correspondent_account', models.CharField(default='', max_length=255)),
                ('inn', models.CharField(default='', max_length=255)),
                ('bik', models.CharField(default='', max_length=255)),
                ('expense_account', models.CharField(default='', max_length=255)),
                ('comment', models.TextField(default='', max_length=10000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cash_income', models.IntegerField(default=0)),
                ('cash_free_income', models.IntegerField(default=0)),
                ('np', models.IntegerField(default=0)),
                ('tables', models.IntegerField(default=0)),
                ('guests', models.IntegerField(default=0)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
                ('contragent', models.CharField(default='', max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.incomecategory')),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Importer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=255)),
                ('bank_name', models.CharField(default='', max_length=255)),
                ('correspondent_account', models.CharField(default='', max_length=255)),
                ('inn', models.CharField(default='', max_length=255)),
                ('bik', models.CharField(default='', max_length=255)),
                ('expense_account', models.CharField(default='', max_length=255)),
                ('production_type', models.CharField(default='', max_length=255)),
                ('custom_production_type', models.CharField(default='', max_length=255)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
                ('is_verified', models.BooleanField(default=False)),
                ('contragent', models.CharField(default='', max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.expensecategory')),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=255)),
                ('subdivision', models.CharField(default='', max_length=255)),
                ('payment_type', models.CharField(default='', max_length=255)),
                ('pay_rate', models.IntegerField(default=0)),
                ('date_accepted', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateTimeField(auto_now_add=True)),
                ('address_residing', models.CharField(default='', max_length=255)),
                ('actual_address', models.CharField(default='', max_length=255)),
                ('comment', models.TextField(default='')),
                ('is_foreign', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, height_field=255, null=True, upload_to='', width_field=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_fired', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
            ],
        ),
    ]
