# Generated by Django 3.1.7 on 2021-03-24 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210310_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='importer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfacility',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('added_at', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('tax_amount', models.FloatField(default=0)),
                ('comment', models.TextField(default='', max_length=10000)),
                ('payment_type', models.CharField(default='cash', max_length=255)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.facility')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.importer')),
            ],
        ),
    ]
