# Generated by Django 3.1.7 on 2021-03-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210325_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Оклад'), ('2', 'Почасовая ставка'), ('3', 'Посуточная ставка')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.CharField(choices=[('1', 'Администрация'), ('2', 'Бар'), ('3', 'Официанты'), ('4', 'Кухня'), ('5', 'Технический Персонал')], default='1', max_length=255),
        ),
    ]
