# Generated by Django 3.1.7 on 2021-03-10 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210310_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='date',
        ),
        migrations.AddField(
            model_name='income',
            name='added_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='revenue',
            name='added_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
