# Generated by Django 3.1.7 on 2021-05-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_salarydeductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydeductions',
            name='deduction_type',
            field=models.CharField(choices=[('1', 'Аванс'), ('2', 'ЗП Безнал'), ('3', 'Мед кн'), ('4', 'VR'), ('5', 'Бой'), ('6', 'Форма'), ('7', 'Удержание по сверкам'), ('8', 'Удержание по акту списания'), ('9', 'Штраф'), ('10', '%'), ('11', 'Доплата')], default='1', max_length=255),
        ),
    ]
