# Generated by Django 3.1.7 on 2021-03-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210325_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
