# Generated by Django 3.1.7 on 2021-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210325_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='subdivision',
            field=models.CharField(choices=[('1', 'Администрация'), ('2', 'Бар'), ('3', 'Официанты'), ('4', 'Кухня'), ('5', 'Технический Персонал')], default=1, max_length=255),
        ),
    ]
