# Generated by Django 3.2 on 2021-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210325_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Накладная'), ('2', 'Расходы'), ('3', 'Сканы'), ('4', 'Уставные Документы')], default='1', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
