# Generated by Django 3.1.7 on 2021-05-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
